---
# It's recommended to leave this as "false"
# Set false to disable hunger in game
hunger: false

# This plugin was made by David Flash [Flash Craft 2]
# Most of the code was used from 1vs1 plugin by GamakCZ
...